/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Body: typeof import('@nestjs/common')['Body']
  const Controller: typeof import('@nestjs/common')['Controller']
  const Delete: typeof import('@nestjs/common')['Delete']
  const Get: typeof import('@nestjs/common')['Get']
  const Inject: typeof import('@nestjs/common')['Inject']
  const Injectable: typeof import('@nestjs/common')['Injectable']
  const Module: typeof import('@nestjs/common')['Module']
  const Next: typeof import('@nestjs/common')['Next']
  const Param: typeof import('@nestjs/common')['Param']
  const Patch: typeof import('@nestjs/common')['Patch']
  const Post: typeof import('@nestjs/common')['Post']
  const Put: typeof import('@nestjs/common')['Put']
  const Query: typeof import('@nestjs/common')['Query']
  const Render: typeof import('@nestjs/common')['Render']
  const Req: typeof import('@nestjs/common')['Req']
  const Res: typeof import('@nestjs/common')['Res']
  const UseFilters: typeof import('@nestjs/common')['UseFilters']
  const UseGuards: typeof import('@nestjs/common')['UseGuards']
  const UseInterceptors: typeof import('@nestjs/common')['UseInterceptors']
  const UsePipes: typeof import('@nestjs/common')['UsePipes']
  const categoryModule: typeof import('./modules/category/category.module')['default']
  const postModule: typeof import('./modules/posts/post.module')['default']
}
